
[webservers]
10.14.61.121 hostname=app01
10.14.61.46 hostname=app02

[dbservers]
10.14.61.74 hostname=db01

[loadbalancers]
10.14.61.56 hostname=lb01

[all:vars]
ansible_ssh_common_args="-J pon-harish@192.168.18.65"